import os
from .globalVar import GCROSSCHAINSENDSIGLIST, GCROSSCHAINRECEIVESIGLIST, GCROSSCHAINRECEIVEEVENTLIST, GCROSSCHAINSENDEVENTLIST

def get_list(str):
    parts = str.replace(" ", "").split(";")
    filtered_parts = [part for part in parts if part]
    return filtered_parts

def get_args():
    SEND_SIGS = os.environ.get('SEND_FUNCS')
    RECEIVE_SIGS = os.environ.get('RECEIVE_FUNCS')
    EVENTS = os.environ.get('EVENTS')
    SEND_STORES = os.environ.get('SEND_STORES')

    CROSSCHAINSENDSIGLIST = get_list(SEND_SIGS) if SEND_SIGS else GCROSSCHAINSENDSIGLIST
    CROSSCHAINRECEIVESIGLIST = get_list(RECEIVE_SIGS) if RECEIVE_SIGS else GCROSSCHAINRECEIVESIGLIST
    CROSSCHAINSENDEVENTLIST = get_list(EVENTS) if EVENTS else GCROSSCHAINSENDEVENTLIST
    CROSSCHAINRECEIVEEVENTLIST =  get_list(SEND_STORES) if SEND_STORES else GCROSSCHAINRECEIVEEVENTLIST
    return CROSSCHAINSENDSIGLIST, CROSSCHAINRECEIVESIGLIST, CROSSCHAINSENDEVENTLIST, CROSSCHAINRECEIVEEVENTLIST